name: CI actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # 의존성 설치
  install-dependencies: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore node modules from cache
        id: resotre-node-modules
        uses: actions/cache@v3
        with:
          path: week-3/node_modules
          key: ${{runner.os}}-node-${{hashFiles('week-3/package-lock.json')}}
          restore-keys: ${{runner.os}}-node

      - name: Install dependencies
        if: steps.resotre-node-modules.outputs.cache-hit != 'true'
        run: npm install
        working-directory: week-3

  # lint 확인 및 수정
  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore node modules from cache
        id: resotre-node-modules
        uses: actions/cache@v3
        with:
          path: week-3/node_modules
          key: ${{runner.os}}-node-${{hashFiles('week-3/package-lock.json')}}
          restore-keys: ${{runner.os}}-node

      - name: Run Lint
        if: steps.resotre-node-modules.outputs.cache-hit != 'true'
        run: npm run lint
        working-directory: week-3

  # 테스트 검증
  test:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore node modules from cache
        id: resotre-node-modules
        uses: actions/cache@v3
        with:
          path: week-3/node_modules
          key: ${{runner.os}}-node-${{hashFiles('week-3/package-lock.json')}}
          restore-keys: ${{runner.os}}-node

      - name: Run Lint
        run: npm run test
        working-directory: week-3

  # Build
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore node modules from cache
        id: resotre-node-modules
        uses: actions/cache@v3
        with:
          path: week-3/node_modules
          key: ${{runner.os}}-node-${{hashFiles('week-3/package-lock.json')}}
          restore-keys: ${{runner.os}}-node

      - name: Run Build
        run: npm run build
        working-directory: week-3
